compressionLevel: mixed

httpRetry: 30

nodeLinker: node-modules

npmRegistryServer: 'http://localhost:4873'
npmRegistries:
  //registry.yarnpkg.com:
    npmAuthToken: '${NPM_TOKEN-}'
yarnPath: .yarn/releases/yarn-4.9.1.cjs
unsafeHttpWhitelist: ["localhost"]